2018-09-21 21:13:14,135 INFO: mangalert startup [in /mnt/c/Users/Bobby Shi/projects/mangalert/app/__init__.py:82]
2018-09-21 21:13:22,061 INFO: mangalert startup [in /mnt/c/Users/Bobby Shi/projects/mangalert/app/__init__.py:82]
2018-09-21 21:13:40,949 INFO: mangalert startup [in /mnt/c/Users/Bobby Shi/projects/mangalert/app/__init__.py:82]
2018-09-21 21:14:40,059 INFO: mangalert startup [in ./app/__init__.py:82]
2018-09-21 21:14:52,531 INFO: mangalert startup [in ./app/__init__.py:82]
2018-09-21 21:16:29,829 INFO: mangalert startup [in /mnt/c/Users/Bobby Shi/projects/mangalert/app/__init__.py:82]
2018-09-21 21:17:17,419 INFO: mangalert startup [in /mnt/c/Users/Bobby Shi/projects/mangalert/app/__init__.py:82]
2018-09-21 21:17:26,662 INFO: mangalert startup [in ./app/__init__.py:82]
2018-09-21 21:17:43,747 INFO: mangalert startup [in ./app/__init__.py:82]
2018-09-21 21:19:11,210 INFO: mangalert startup [in /mnt/c/Users/Bobby Shi/projects/mangalert/app/__init__.py:82]
2018-09-21 21:20:27,809 INFO: mangalert startup [in /mnt/c/Users/Bobby Shi/projects/mangalert/app/__init__.py:82]
2018-09-21 21:20:32,496 INFO: mangalert startup [in /mnt/c/Users/Bobby Shi/projects/mangalert/app/__init__.py:82]
2018-09-21 21:20:51,744 INFO: mangalert startup [in /mnt/c/Users/Bobby Shi/projects/mangalert/app/__init__.py:82]
2018-09-21 21:21:47,249 INFO: mangalert startup [in ./app/__init__.py:82]
2018-09-21 21:21:53,480 INFO: mangalert startup [in ./app/__init__.py:82]
2018-09-21 21:22:24,053 INFO: mangalert startup [in /mnt/c/Users/Bobby Shi/projects/mangalert/app/__init__.py:82]
2018-09-21 21:23:53,474 INFO: mangalert startup [in /mnt/c/Users/Bobby Shi/projects/mangalert/app/__init__.py:82]
2018-09-21 21:24:40,321 INFO: mangalert startup [in ./app/__init__.py:82]
2018-09-21 21:26:52,038 INFO: mangalert startup [in /mnt/c/Users/Bobby Shi/projects/mangalert/app/__init__.py:82]
2018-09-21 21:27:38,984 ERROR: Unhandled exception [in ./app/tasks.py:76]
Traceback (most recent call last):
  File "./app/tasks.py", line 70, in get_follows
    time.sleep(1)
  File "/home/bshi/miniconda3/lib/python3.6/site-packages/rq/timeouts.py", line 64, in handle_death_penalty
    '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (180 seconds)
2018-09-21 21:31:04,151 INFO: mangalert startup [in ./app/__init__.py:82]
2018-09-21 21:34:02,364 ERROR: Unhandled exception [in ./app/tasks.py:76]
Traceback (most recent call last):
  File "./app/tasks.py", line 38, in get_follows
    if isPNG(code):
  File "./app/src/utils.py", line 14, in isPNG
    r = requests.get('https://mangadex.org/images/manga/{}.png'.format(code))
  File "/home/bshi/miniconda3/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/bshi/miniconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bshi/miniconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bshi/miniconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/bshi/miniconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/bshi/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/bshi/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/bshi/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/home/bshi/miniconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/bshi/miniconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/bshi/miniconda3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/bshi/miniconda3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/bshi/miniconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 280, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/home/bshi/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1714, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
  File "/home/bshi/miniconda3/lib/python3.6/site-packages/rq/timeouts.py", line 64, in handle_death_penalty
    '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (180 seconds)
